redirects:
    developers-guide/plugin-guidelines/: https://developers.shopware.com/developers-guide/plugin-guidelines/
    guides/plugins/apps/platform-sh-template.html: guides/plugins/apps/app-base-guide.html
    guides/integrations-api/store-api-guide.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/register-a-customer.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/search-for-products.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/work-with-the-cart.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/handling-the-payment.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/faq.html: guides/integrations-api/
    guides/integrations-api/admin-api/: guides/integrations-api/
    guides/integrations-api/admin-api/action-routes.html: guides/integrations-api/
    guides/integrations-api/admin-api/authentication.html: guides/integrations-api/
    guides/integrations-api/admin-api/reading-entities.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/associations.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/bulk-payloads.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/product-data.html: guides/integrations-api/
    resources/references/api-reference/admin-api-reference.html: guides/integrations-api/
    concepts/extensions/elasticsearch-concept.html: concepts/framework/elasticsearch.html
    guides/plugins/plugins/storefront/use-csrf-protection.html: guides/hosting/configurations/framework/samesite-protection.html
    products/extensions/b2b-suite/*: products/extensions/b2b/b2b-suite/*
    products/extensions/b2b-components/*: products/extensions/b2b/b2b-components/*
    guides/plugins/plugins/administration/add-shortcuts.html: guides/plugins/plugins/administration/advanced-configuration/add-shortcuts.html
    guides/plugins/plugins/administration/extending-webpack.html: guides/plugins/plugins/administration/advanced-configuration/extending-webpack.html
    guides/plugins/plugins/administration/modify-blacklist-for-dynamic-product-groups.html: guides/plugins/plugins/administration/advanced-configuration/modify-blacklist-for-dynamic-product-groups.html
    guides/plugins/plugins/administration/handling-media.html: guides/plugins/plugins/administration/data-handling-processing/handling-media.html
    guides/plugins/plugins/administration/search-custom-data.html: guides/plugins/plugins/administration/data-handling-processing/search-custom-data.html
    guides/plugins/plugins/administration/using-custom-fields.html: guides/plugins/plugins/administration/data-handling-processing/using-custom-fields.html
    guides/plugins/plugins/administration/using-data-handling.html: guides/plugins/plugins/administration/data-handling-processing/using-data-handling.html
    guides/plugins/plugins/administration/using-the-data-grid-component.html: guides/plugins/plugins/administration/data-handling-processing/using-the-data-grid-component.html
    guides/plugins/plugins/administration/using-vuex-state.html: guides/plugins/plugins/administration/data-handling-processing/using-vuex-state.html
    guides/plugins/plugins/administration/add-mixins.html: guides/plugins/plugins/administration/mixins-directives/add-mixins.html
    guides/plugins/plugins/administration/adding-directives.html: guides/plugins/plugins/administration/mixins-directives/adding-directives.html
    guides/plugins/plugins/administration/using-mixins.html: guides/plugins/plugins/administration/mixins-directives/using-mixins.html
    guides/plugins/plugins/administration/add-custom-component.html: guides/plugins/plugins/administration/module-component-management/add-custom-component.html
    guides/plugins/plugins/administration/add-custom-field.html: guides/plugins/plugins/administration/module-component-management/add-custom-field.html
    guides/plugins/plugins/administration/add-custom-module.html: guides/plugins/plugins/administration/module-component-management/add-custom-module.html
    guides/plugins/plugins/administration/customizing-modules.html: guides/plugins/plugins/administration/module-component-management/customizing-modules.html
    guides/plugins/plugins/administration/using-base-components.html: guides/plugins/plugins/administration/module-component-management/using-base-components.html
    guides/plugins/plugins/administration/add-error-handling.html: guides/plugins/plugins/administration/permissions-error-handling/add-error-handling.html
    guides/plugins/plugins/administration/add-custom-route.html: guides/plugins/plugins/administration/routing-navigation/add-custom-route.html
    guides/plugins/plugins/administration/add-menu-entry.html: guides/plugins/plugins/administration/routing-navigation/add-menu-entry.html
    guides/plugins/plugins/administration/add-new-tab.html: guides/plugins/plugins/administration/routing-navigation/add-new-tab.html
    guides/plugins/plugins/administration/overriding-routes.html: guides/plugins/plugins/administration/routing-navigation/overriding-routes.html
    guides/plugins/plugins/administration/add-custom-service.html: guides/plugins/plugins/administration/services-utilities/add-custom-service.html
    guides/plugins/plugins/administration/add-filter.html: guides/plugins/plugins/administration/services-utilities/add-filter.html
    guides/plugins/plugins/administration/extending-services.html: guides/plugins/plugins/administration/services-utilities/extending-services.html
    guides/plugins/plugins/administration/injecting-services.html: guides/plugins/plugins/administration/services-utilities/injecting-services.html
    guides/plugins/plugins/administration/the-sanitizer-helper.html: guides/plugins/plugins/administration/services-utilities/the-sanitizer-helper.html
    guides/plugins/plugins/administration/using-filter.html: guides/plugins/plugins/administration/services-utilities/using-filter.html
    guides/plugins/plugins/administration/using-utils.html: guides/plugins/plugins/administration/services-utilities/using-utils.html
    guides/plugins/plugins/administration/add-custom-styles.html: guides/plugins/plugins/administration/templates-styling/add-custom-styles.html
    guides/plugins/plugins/administration/adding-snippets.html: guides/plugins/plugins/administration/templates-styling/adding-snippets.html
    guides/plugins/plugins/administration/using-assets.html: guides/plugins/plugins/administration/templates-styling/using-assets.html
    guides/plugins/plugins/administration/writing-templates.html: guides/plugins/plugins/administration/templates-styling/writing-templates.html
    guides/plugins/plugins/administration/adding-responsive-behavior.html: guides/plugins/plugins/administration/ui-ux/adding-responsive-behavior.html




