redirects:
    developers-guide/plugin-guidelines/: https://developers.shopware.com/developers-guide/plugin-guidelines/
    guides/plugins/apps/platform-sh-template.html: guides/plugins/apps/app-base-guide.html
    guides/integrations-api/store-api-guide.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/register-a-customer.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/search-for-products.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/work-with-the-cart.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/handling-the-payment.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/faq.html: guides/integrations-api/
    guides/integrations-api/admin-api/: guides/integrations-api/
    guides/integrations-api/admin-api/action-routes.html: guides/integrations-api/
    guides/integrations-api/admin-api/authentication.html: guides/integrations-api/
    guides/integrations-api/admin-api/reading-entities.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/associations.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/bulk-payloads.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/product-data.html: guides/integrations-api/
    resources/references/api-reference/admin-api-reference.html: guides/integrations-api/
    concepts/extensions/elasticsearch-concept.html: concepts/framework/elasticsearch.html
    guides/plugins/plugins/storefront/use-csrf-protection.html: guides/hosting/configurations/framework/samesite-protection.html
    products/extensions/b2b-suite/*: products/extensions/b2b/b2b-suite/*
    products/extensions/b2b-components/*: products/extensions/b2b/b2b-components/*
    guides/plugins/plugins/administration/add-shortcuts.html: guides/plugins/plugins/administration/advanced-configuration/add-shortcuts.html
    guides/plugins/plugins/administration/extending-webpack.html: guides/plugins/plugins/administration/advanced-configuration/extending-webpack.html
    guides/plugins/plugins/administration/modify-blacklist-for-dynamic-product-groups.html: guides/plugins/plugins/administration/advanced-configuration/modify-blacklist-for-dynamic-product-groups.html
    guides/plugins/plugins/administration/handling-media.html: guides/plugins/plugins/administration/data-handling-processing/handling-media.html
    guides/plugins/plugins/administration/search-custom-data.html: guides/plugins/plugins/administration/data-handling-processing/search-custom-data.html
    guides/plugins/plugins/administration/using-custom-fields.html: guides/plugins/plugins/administration/data-handling-processing/using-custom-fields.html
    guides/plugins/plugins/administration/using-data-handling.html: guides/plugins/plugins/administration/data-handling-processing/using-data-handling.html
    guides/plugins/plugins/administration/using-the-data-grid-component.html: guides/plugins/plugins/administration/data-handling-processing/using-the-data-grid-component.html
    guides/plugins/plugins/administration/using-vuex-state.html: guides/plugins/plugins/administration/data-handling-processing/using-vuex-state.html
    guides/plugins/plugins/administration/add-mixins.html: guides/plugins/plugins/administration/mixins-directives/add-mixins.html
    guides/plugins/plugins/administration/adding-directives.html: guides/plugins/plugins/administration/mixins-directives/adding-directives.html
    guides/plugins/plugins/administration/using-mixins.html: guides/plugins/plugins/administration/mixins-directives/using-mixins.html
    guides/plugins/plugins/administration/add-custom-component.html: guides/plugins/plugins/administration/module-component-management/add-custom-component.html
    guides/plugins/plugins/administration/add-custom-field.html: guides/plugins/plugins/administration/module-component-management/add-custom-field.html
    guides/plugins/plugins/administration/add-custom-module.html: guides/plugins/plugins/administration/module-component-management/add-custom-module.html
    guides/plugins/plugins/administration/customizing-modules.html: guides/plugins/plugins/administration/module-component-management/customizing-modules.html
    guides/plugins/plugins/administration/using-base-components.html: guides/plugins/plugins/administration/module-component-management/using-base-components.html
    guides/plugins/plugins/administration/add-error-handling.html: guides/plugins/plugins/administration/permissions-error-handling/add-error-handling.html
    guides/plugins/plugins/administration/add-custom-route.html: guides/plugins/plugins/administration/routing-navigation/add-custom-route.html
    guides/plugins/plugins/administration/add-menu-entry.html: guides/plugins/plugins/administration/routing-navigation/add-menu-entry.html
    guides/plugins/plugins/administration/add-new-tab.html: guides/plugins/plugins/administration/routing-navigation/add-new-tab.html
    guides/plugins/plugins/administration/overriding-routes.html: guides/plugins/plugins/administration/routing-navigation/overriding-routes.html
    guides/plugins/plugins/administration/add-custom-service.html: guides/plugins/plugins/administration/services-utilities/add-custom-service.html
    guides/plugins/plugins/administration/add-filter.html: guides/plugins/plugins/administration/services-utilities/add-filter.html
    guides/plugins/plugins/administration/extending-services.html: guides/plugins/plugins/administration/services-utilities/extending-services.html
    guides/plugins/plugins/administration/injecting-services.html: guides/plugins/plugins/administration/services-utilities/injecting-services.html
    guides/plugins/plugins/administration/the-sanitizer-helper.html: guides/plugins/plugins/administration/services-utilities/the-sanitizer-helper.html
    guides/plugins/plugins/administration/using-filter.html: guides/plugins/plugins/administration/services-utilities/using-filter.html
    guides/plugins/plugins/administration/using-utils.html: guides/plugins/plugins/administration/services-utilities/using-utils.html
    guides/plugins/plugins/administration/add-custom-styles.html: guides/plugins/plugins/administration/templates-styling/add-custom-styles.html
    guides/plugins/plugins/administration/adding-snippets.html: guides/plugins/plugins/administration/templates-styling/adding-snippets.html
    guides/plugins/plugins/administration/using-assets.html: guides/plugins/plugins/administration/templates-styling/using-assets.html
    guides/plugins/plugins/administration/writing-templates.html: guides/plugins/plugins/administration/templates-styling/writing-templates.html
    guides/plugins/plugins/administration/adding-responsive-behavior.html: guides/plugins/plugins/administration/ui-ux/adding-responsive-behavior.html
    products/plugins/commercial/: products/extensions/commercial/
    guides/installation/devenv.html: guides/installation/setups/devenv.html
    products/cli/extension-commands/validation.html: products/cli/validation.html
    products/paas/: products/paas/index.html
    products/paas/cli-setup.html: products/paas/shopware-paas/cli-setup.html
    products/paas/repository.html: products/paas/shopware-paas/repository.html
    products/paas/build-deploy.html: products/paas/shopware-paas/build-deploy.html
    products/paas/setup-template.html: products/paas/shopware-paas/setup-template.html
    products/paas/elasticsearch.html: products/paas/shopware-paas/elasticsearch.html
    products/paas/rabbitmq.html: products/paas/shopware-paas/rabbitmq.html
    products/paas/fastly.html: products/paas/shopware-paas/fastly.html
    products/paas/blackfire.html: products/paas/shopware-paas/blackfire.html
    guides/plugins/apps/in-app-purchase/: guides/plugins/apps/in-app-purchases.html
    guides/plugins/plugins/in-app-purchase/: guides/plugins/plugins/in-app-purchases.html
    products/paas/shopware/CLI/account.html: products/paas/shopware/fundamentals/account.html
    products/paas/shopware/CLI/applications.html: products/paas/shopware/fundamentals/applications.html
    products/paas/shopware/CLI/command.html: products/paas/shopware/get-started/cli.html
    products/paas/shopware/CLI/exec.html: products/paas/shopware/get-started/cli.html
    products/paas/shopware/CLI/index.html: products/paas/shopware/get-started/cli.html
    products/paas/shopware/CLI/open.html: products/paas/shopware/get-started/cli.html
    products/paas/shopware/CLI/organizations.html: products/paas/shopware/fundamentals/organization.html
    products/paas/shopware/CLI/project.html: products/paas/shopware/fundamentals/project.html
    products/paas/shopware/CLI/vault.html: products/paas/shopware/fundamentals/secrets.html
    products/paas/shopware/CLI/watch.html: products/paas/shopware/monitoring/watch.html
    products/paas/shopware/CLI/repository.html: products/paas/shopware/guides/setting-up-repository-access.html
    products/paas/shopware/setup-shopware-for-paas.html: products/paas/shopware/get-started/prepare-codebase.html
    products/paas/shopware/project_setup.html: products/paas/shopware/get-started/quickstart.html
    guides/plugins/plugins/testing/end-to-end-testing.html: guides/plugins/plugins/testing/cypress/cypress-end-to-end-testing.html
    resources/guidelines/testing/cypress-best-practices.html: guides/plugins/plugins/testing/cypress/cypress-best-practises.html
    resources/guidelines/trouble-shoting.html: resources/guidelines/troubleshooting.html
    products/extensions/subscriptions/guides/event.html: products/extensions/subscriptions/guides/separate-checkout.html
    products/extensions/subscriptions/guides/request-scoping.html: products/extensions/subscriptions/guides/separate-checkout.html
    concepts/framework/rules.html: concepts/framework/rule/index.html
    products/extensions/migration-assistant/concept.html: products/extensions/migration-assistant/concept/index.html
    products/extensions/migration-assistant/guides.html: products/extensions/migration-assistant/guides/index.html
    products/cli/project-commands/project-config-sync.html: resources/tooling/fixture-bundle/index.html
    products/sales-agent/deployment.html: products/sales-agent/best-practices/app-deployment/hosted-with-ubuntu-server.html
    guides/installation/requirements.html: guides/installation/system-requirements.html
    guides/installation/setups/docker.html: guides/installation/docker-setup.html
    guides/installation/template.html: guides/installation/project-overview.html
    guides/installation/setups/docker-options.html: guides/installation/advanced-options.html
    guides/installation/setups/devenv.html: guides/installation/legacy-setups/devenv-setup.html
    guides/installation/setups/symfony-cli.html: guides/installation/legacy-setups/symfony-cli-setup.html
    guides/installation/setups/devenv-options.html: guides/installation/legacy-setups/devenv-options.html
    guides/installation/setups/: guides/installation/