redirects:
    developers-guide/plugin-guidelines/: https://developers.shopware.com/developers-guide/plugin-guidelines/
    guides/plugins/apps/platform-sh-template.html: guides/plugins/apps/app-base-guide.html
    guides/integrations-api/store-api-guide.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/register-a-customer.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/search-for-products.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/work-with-the-cart.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/handling-the-payment.html: guides/integrations-api/
    guides/integrations-api/store-api-guide/faq.html: guides/integrations-api/
    guides/integrations-api/admin-api/: guides/integrations-api/
    guides/integrations-api/admin-api/action-routes.html: guides/integrations-api/
    guides/integrations-api/admin-api/authentication.html: guides/integrations-api/
    guides/integrations-api/admin-api/reading-entities.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/associations.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/bulk-payloads.html: guides/integrations-api/
    guides/integrations-api/admin-api/writing-entities/product-data.html: guides/integrations-api/
    resources/references/api-reference/admin-api-reference.html: guides/integrations-api/
    concepts/extensions/elasticsearch-concept.html: concepts/framework/elasticsearch.html
    guides/plugins/plugins/storefront/use-csrf-protection.html: guides/hosting/configurations/framework/samesite-protection.html
    products/extensions/b2b-suite/: products/extensions/b2b/b2b-suite/
    products/extensions/b2b-components/: products/extensions/b2b/b2b-components/
