name: Deploy to DevHub

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    name: Trigger deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm i @octokit/rest

      - name: Trigger deployment
        run: |
          node .github/scripts/trigger-workflow.js
        env:
          WORKFLOW: "checkout-test-build-deploy.yml"
          PERSONAL_ACCESS_TOKEN: ${{ secrets.DEV_HUB_PERSONAL_ACCESS_TOKEN }}
          DEV_HUB_BRANCH: ${{ inputs.branch }}
          DEV_HUB_REPO: ${{ inputs.repo }}
          DEV_HUB_SHA: ${{ inputs.sha }}
          DEV_HUB_CHECK: ${{ inputs.check }}
          DEV_HUB_CONCLUSION: ${{ steps.status.outputs.success == 'true' && 'success' || 'failure' }}